#pragma once

enum class eFishingState : int {
    None = 0,
    Casting = 1,
    Search = 2,
    SearchResult = 3,
    Idle = 4,
    Hit = 5,
    Fighting = 6,
    Catch = 7,
    Fail = 8,
    Boast = 9,
    Finish = 10,
    CastingFail = 11,
    Miss = 12,
    BigFish_RaidEnter = 13,
    BigFish_RaidSync = 14,
    BigFish_Begin = 15,
    BigFish_Pumpin = 16,
    BigFish_Drag = 17,
    BigFish_Tug = 18,
    BigFish_Fighting = 19,
    BigFish_Catch = 20,
    BigFish_Miss = 21,
    BigFish_RaidFighting = 22,
    BigFish_StunBegin = 23,
    BigFish_Stun = 24,
    BigFish_StunRecovery = 25,
};
