//
// Created by HMGTEAM on 11/05/2025.
//

#ifndef PLAY_PRO_MAX_ITEM_TYPE_H
#define PLAY_PRO_MAX_ITEM_TYPE_H
enum class Item_Type : int32_t {
    Currency = 0,
    Costume = 1,
    MyHome = 2,
    MyHouse = 3,
    Vehicle = 4,
    Pet = 5,
    Emote = 6,
    MyHouseSize = 7,
    Gacha = 8,
    Junk = 9,
    Pass_Point = 10,
    Set_Item = 11,
    Food = 12,
    Ingredient = 13,
    Toy = 14,
    GamePass_Point = 15,
    Trophy_Pass = 16,
    Fish = 17,
    Quest = 18,
    CardTheme = 19,
    DirectMessage = 20,
    PeriodItem = 21,
    InGameItem = 22,
    TravelTicket = 23,
    SubscriptionPackage = 24,
    ItemGrowingMaterial = 25,
    CameraFilter = 26,
    HouseMusic = 27,
    CameraSticker = 28,
    CameraMotion = 29,
    EventCurrency = 30,
    HouseBluePrint = 31,
    Soundscape = 32,
    HairColor = 33,
    ChatColorItem = 34,
    Picnic = 35,
    GachaCoupon = 36,
    Insect = 37,
    BattleUpItem = 38,
    GameCurrencyItem = 39,
    InstantItem = 40,
    HomePartyItem = 41,
    RolePlay = 42,
    OreItem = 43,
    PlantsItem = 44,
    ToolItem = 45,
    BaitItem = 46,
    Showroom = 47,
    CoupleItem = 48,
    ProfileImage = 49,
    RolePlayFunction = 50,
    NickNameBadgeItem = 51,
    AutoChargeItem = 52,
    ChoicePackage = 53,
    CollectingCardItem = 54,
    PaidStampItem = 55,
    PetDetectSkillItem = 56,
    Weapon = 57,
    Baby = 58,
    BabyCostume = 59,
    BabyToy = 60,
    BabyFood = 61,
    AutoCatch = 62,
    CardGacha = 63,
    RouletteItem = 64,
    FarmSeed = 65,
    FarmFruit = 66,
    FarmGear = 67,
    BabyCarrier = 68,
    MyHouseProp = 69,
    ItemGiftTicket = 70,
    BagFavoritesItem = 99,
    End = 100,
};
#endif //PLAY_PRO_MAX_ITEM_TYPE_H
